### ISSUE TITLE
Use new Travis CI icon

### ISSUE THREAD

**Issue by richiksc** [file-icons/DevOpicons#2]

**Comment by Alhadis** [comment]
Hi @richiksc,

Which icon is that?

**Comment by richiksc** [comment]
The Travis CI mascot (The mustached construction worker with the "T" helmet). Like this one: https://icons8.com/icon/30276/travis-ci.

**Comment by Alhadis** [comment]
Oh, that one. 

I remember trying to make that icon look halfway decent at low-resolution, but it turned out to be impossible. Trying to squash that many details into 16×16 pixels' worth of space left it completely unrecognisable, which is why we're still using it today.

In any case, this particular icon-font won't be receiving updates as the package's [main font](https://github.com/file-icons/source) is where updates and additions are made. DevOpicons and Mfixx exist mainly for compatibility reasons, due to the way this package started.
